AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM CloudFormation Template"

Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "isai-admin"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

  MyIAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "TestGroup"

  UserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref MyIAMGroup
      Users:
        - !Ref MyIAMUser

  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ["ec2.amazonaws.com"]
            Action: ["sts:AssumeRole"]
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/PowerUserAccess"

  MyIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "CustomPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
            Resource: "*"
      Roles:
        - !Ref MyIAMRole
